. $HOME/bin/dotfiles/bash/env
. $HOME/bin/dotfiles/bash/config
. $HOME/bin/dotfiles/bash/aliases

export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"
