. $HOME/bin/dotfiles/bash/env
. $HOME/bin/dotfiles/bash/config
. $HOME/bin/dotfiles/bash/aliases

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export PATH="/home/cdolan/.pyenv/bin:$PATH"
